### ISSUE TITLE
Assembly File Error?

### ISSUE THREAD

**Issue by patrickmichalina** [rdumont/NuGetContentGenerator#4]
When using `nuget pack` from the .csproj with .nuspec at the same level (to auto include dependency tree), I get this:

```
The result "" of evaluating the value "@(AssemblyFile)" of the "AssemblyFile" attribute in element <UsingTask> is not valid.  C:\Users\Patrick\Source\Repos\...\...\packages\NuGetContentGenerator.0.2.0\build\NuGetContentGenerator.targets
```

Any ideas?

**Comment by driscollwebdev** [comment]
@patrickmichalina I am having the same issue - were you ever able to resolve it?

**Comment by dittodhole** [comment]
see PR #6

**Comment by rdumont** [comment]
@patrickmichalina, @driscollwebdev, @dittodhole, can you confirm that #6 fixes this?

**Comment by dittodhole** [comment]
@rdumont yep, verified this with a private build for one of my projects.

the reason is simple: when using `nuget pack foo.csproj`, the msbuild variable `$(SoultionDir)` is not available :)

**Comment by ericnewton76** [comment]
Hi easy solution that could use a PR merge and nuget publish please.

**Comment by thomasgalliker** [comment]
Is this project still maintained? Anyone to fork it? The idea looks pretty much what I need to create source-only nuget packages.

**Comment by patrickmichalina** [comment]
I never resolved this and have left .NET for greener pastures in Node land. Good luck!
